name: CI

on:
  push:
    tags:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 'latest'
          bb: 'latest'

      - uses: actions/checkout@v3

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Deploy
        run: bb deploy:clojars
